services:
  thrive.bootstrapper:
    image: thrive.bootstrapper
    build:
      context: .
      dockerfile: src/Bootstrapper/Thrive.Bootstrapper/Dockerfile
  postgres:
    image: postgres
    env_file:
      - .env
    container_name: postgres-db
    ports:
      - '5432:5432'
  redis:
    image: redis/redis-stack
    container_name: redis
    ports:
      - '6379:6379'
    volumes:
      - /var/lib/redis
    environment:
      REDIS_ARGS: "--requirepass ${REDIS_PASSWORD} --user ${REDIS_USERNAME} on >${REDIS_PASSWORD} ~* allcommands --user default off nopass nocommands"
    env_file:
      - .env
