services:
  db:
    image: postgres
    restart: always
    env_file:
      - .env
    container_name: postgres-db
    ports:
      - '5432:5432'
    networks:
      - backend
  redis:
    image: redis/redis-stack
    container_name: redis
    ports:
      - '6379:6379'
    volumes:
      - /var/lib/redis
    networks:
      - backend
    environment:
      REDIS_ARGS: "--requirepass ${REDIS_PASSWORD} --user ${REDIS_USERNAME} on >${REDIS_PASSWORD} ~* allcommands --user default off nopass nocommands"
    env_file:
      - .env
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    build:
      context: .
      dockerfile: ./rabbitmq/Dockerfile
    hostname: rabbitmq
    volumes:
      - /var/lib/rabbitmq
    ports:
      - '5672:5672'
      - '15672:15672'
    networks:
      - backend
    env_file:
      - .env
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:15672" ]
      interval: 30s
      timeout: 10s
      retries: 5
  nginx:
    container_name: nginx
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - '3100:3100'
    depends_on:
      - identity-service
    networks:
      - backend
  identity-service:
    container_name: identity-service
    build:
      context: .
      dockerfile: apps/identity/Dockerfile
      target: development
    command: pnpm run start:dev identity
    depends_on:
      rabbitmq:
        condition: service_healthy
    ports:
      - '3101:3101'
    networks:
      - backend
    env_file:
      - .env
      - ${IDENTITY_ENV}
    volumes:
      - .:/usr/src/app
  notifications-service:
    container_name: notifications-service
    build:
      context: .
      dockerfile: apps/notifications/Dockerfile
      target: development
    command: pnpm run start:dev notifications
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - backend
    env_file:
      - .env
      - ${NOTIFICATIONS_ENV}
    volumes:
      - .:/usr/src/app

networks:
  backend:
    driver: bridge