http {
    upstream identity {
        server identity-service:3101;
    }

    server {
        listen 3100;

        location /identity/ {
            proxy_pass http://identity/;
        }
    }
}

events {
}