// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Thrive.Modules.Identity.Infrastructure.Database;

#nullable disable

namespace Thrive.Modules.Identity.Infrastructure.Database.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20241201020814_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("identity")
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Thrive.Modules.Identity.Domain.Entities.IdentityUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password");

                    b.HasKey("Id");

                    b.ToTable("user", "identity");
                });

            modelBuilder.Entity("Thrive.Modules.Identity.Domain.Entities.IdentityUser", b =>
                {
                    b.OwnsOne("Thrive.Modules.Identity.Domain.Entities.UserEmail", "Email", b1 =>
                        {
                            b1.Property<Guid>("IdentityUserId")
                                .HasColumnType("uuid");

                            b1.Property<bool>("IsVerified")
                                .HasColumnType("boolean")
                                .HasColumnName("email_verified");

                            b1.HasKey("IdentityUserId");

                            b1.ToTable("user", "identity");

                            b1.WithOwner()
                                .HasForeignKey("IdentityUserId");

                            b1.OwnsOne("Thrive.Modules.Identity.Domain.ValueObjects.EmailAddress", "Address", b2 =>
                                {
                                    b2.Property<Guid>("UserEmailIdentityUserId")
                                        .HasColumnType("uuid");

                                    b2.Property<string>("Value")
                                        .IsRequired()
                                        .HasColumnType("text")
                                        .HasColumnName("email_address");

                                    b2.HasKey("UserEmailIdentityUserId");

                                    b2.ToTable("user", "identity");

                                    b2.WithOwner()
                                        .HasForeignKey("UserEmailIdentityUserId");
                                });

                            b1.Navigation("Address")
                                .IsRequired();
                        });

                    b.OwnsOne("Thrive.Modules.Identity.Domain.ValueObjects.Username", "Username", b1 =>
                        {
                            b1.Property<Guid>("IdentityUserId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("username");

                            b1.HasKey("IdentityUserId");

                            b1.ToTable("user", "identity");

                            b1.WithOwner()
                                .HasForeignKey("IdentityUserId");
                        });

                    b.Navigation("Email")
                        .IsRequired();

                    b.Navigation("Username")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
